version = 1

[[annotations]]
path = [
  "src/**/*.ts",
  "src/**/*.vue",
  "src/**/*.json",
  "src/**/*.toml"
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Gabriel Rodrigues Antunes <gabrielrodantunes@gmail.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
  "**/*.md",
  "**/.gitignore",
  "**/*.lock",
  "**/*.txt",
  "**/*.ico",
  ".github/**/*.yml",
  ".container/**/*",
  ".devcontainer/**/*",
  ".gitattributes",
  ".dockerignore",
  ".editorconfig",
  "CODEOWNERS"
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Gabriel Rodrigues Antunes <gabrielrodantunes@gmail.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = [
  "docs/assets/**/*",
  "src/**/*.png",
  "src/**/*.svg",
  "src/**/*.webp"
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Gabriel Rodrigues Antunes <gabrielrodantunes@gmail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
