kind: project
emit:
  - "@typespec/json-schema"
options:
  "@typespec/json-schema":
    emitter-output-dir: "{output-dir}/schema"
    file-type: "json"
    int64-strategy: "string"
    emitAllModels: true
    emitAllRefs: true
    seal-object-schemas: true
    bundleId: "caderno.schemas.json"

