name: "Run command in DevContainer"
description: "Run any command inside a DevContainer"

inputs:
  imageName:
    required: true
    default: "ci.caderno.meu-caderno.local/devcontainer"
  command:
    required: true

runs:
  using: composite
  steps:
    - name: "Run in DevContainer"
      uses: devcontainers/ci@v0.3
      with:
        configFile: ./.devcontainer/ci/devcontainer.json
        cacheFrom: ${{ inputs.imageName }}
        push: never
        runCmd: |
          set -euo pipefail
          ${{ inputs.command }}
