name: "Run command in DevContainer"
description: "Run any command inside a DevContainer"

inputs:
  imageName:
    required: true
    default: "ci.caderno.meu-caderno.local/devcontainer"
  command:
    required: true

runs:
  using: composite
  steps:
      - name: "Prepare DevContainer"
        uses: .github/actions/prepare-devcontainer
        with:
          imageName: ${{ inputs.imageName }}

      - name: "Build PWA in DevContainer"
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ${{ inputs.imageName }}
          push: never
          runCmd: |
            ${{ inputs.command }}
