name: "Prepare DevContainer"
description: ""

inputs:
  imageName:
    required: true
    default: "ci.caderno.meu-caderno.local/devcontainer"
  installDependencies:
    required: true
    default: "true"

runs:
  using: composite
  steps:
    - name: "Pre-build DevContainer image"
      uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca
      with:
        configFile: ./.devcontainer/ci/devcontainer.json
        imageName: ${{ inputs.imageName }}
        cacheFrom: ${{ inputs.imageName }}
        push: never

    - name: "Install dependencies"
      uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca
      if: ${{ fromJSON(inputs.installDependencies) == true }}
      with:
        configFile: ./.devcontainer/ci/devcontainer.json
        cacheFrom: ${{ inputs.imageName }}
        push: never
        runCmd: |
          cd src;
          bun install --frozen-lockfile;
