name: "Run command in DevContainer"
description: "Run any command inside a DevContainer"

inputs:
  imageName:
    required: true
    default: "ci.caderno.meu-caderno.local/devcontainer"
    description: ""

runs:
  using: composite
  steps:
    - name: "Prepare DevContainer"
      uses: ./.github/actions/prepare-devcontainer
      with:
        imageName: ${{ inputs.imageName }}
