name: "CD"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**/*
      - .container/**/*
      - .devcontainer/**/*
      - .github/workflows/cd.yml
      - .github/actions/run-in-devcontainer/**/*

concurrency:
  group: cd
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  IMAGE_BASENAME: ${{ github.repository }}
  IMAGE_SERVICE: caderno-app-devcontainer

jobs:
  ci:
    name: "Build container image"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout do código-fonte"
        uses: actions/checkout@v7.0.0

      - name: "Build PWA in DevContainer"
        uses: ./.github/actions/run-in-devcontainer
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/${{ env.IMAGE_SERVICE }}
          command: |
            cd src/pkgs/apps/pwa;
            bun install;
            bun run build;
