name: "Flow - Deploy"

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: "Prepare source-code with SDK"
        uses: ./.github/actions/prepare

      - name: "Build PWA in DevContainer"
        uses: ./.github/actions/run-in-devcontainer
        with:
          command: |
            cd src/pkgs/apps/pwa;
            bun install;
            bun run build;

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: src/pkgs/apps/pwa/.output/public

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
