name: "Flow - Quality"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: "Prepare source-code with SDK"
        uses: ./.github/actions/prepare

      - name: "Check for format and lint issues"
        uses: ./.github/actions/run-in-devcontainer
        with:
          command: |
            cd src;
            bun run quality:check:ci;

      - name: "Build PWA in DevContainer"
        uses: ./.github/actions/run-in-devcontainer
        with:
          command: |
            cd src;
            bun run all:build;
