# configuracoes de usuario
ARG USERNAME=happy
ARG USER_ID=1000
ARG GROUP_ID=1000
# configurações do bun
ARG BUN_VERSION=bun-v1.3.3

########
# LAYER: Base OS
FROM docker.io/debian:trixie-slim AS os
########

########
# LAYER: Container base para o projeto (compartilhada entre devcontainer e prod)
FROM os AS base

ARG USERNAME
ARG USER_ID
ARG GROUP_ID
ARG BUN_VERSION

USER root

RUN groupadd -g ${GROUP_ID} ${USERNAME} && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} ${USERNAME}
ENV HOME=/home/${USERNAME}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    unzip \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV BUN_INSTALL="/opt/bun"
ENV BUN_INSTALL_CACHE_DIR="/tmp/bun-cache"
ENV TMPDIR=/tmp/bun-tmp

RUN mkdir -p "${BUN_INSTALL}/bin" "${BUN_INSTALL_CACHE_DIR}" "${TMPDIR}" \
    && chmod -R 777 "${BUN_INSTALL_CACHE_DIR}" "${TMPDIR}"

RUN curl -fsSL https://bun.com/install | bash -s -- ${BUN_VERSION}
ENV PATH="${BUN_INSTALL}/bin:$PATH"

USER ${USERNAME}
RUN bun --version
########

########
# LAYER: Container para desenvolvimento (devcontainer)
FROM base AS devcontainer

ARG USERNAME
ARG USER_ID
ARG GROUP_ID

USER root

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update -y && apt-get install -y git vim zsh && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /container/shell-history/root /container/shell-history/${USERNAME} \
    && chown -R ${USER_ID}:${GROUP_ID} /container/shell-history/${USERNAME} \
    && chmod 700 /container/shell-history/root /container/shell-history/${USERNAME}

# .profile do root com HISTFILE
RUN printf '# Shell history via managed Docker volume\n\
    _histdir="/container/shell-history/$(id -un)"\n\
    if [ -n "$ZSH_VERSION" ]; then\n\
    HISTFILE="$_histdir/.zsh_history"\n\
    elif [ -n "$BASH_VERSION" ]; then\n\
    HISTFILE="$_histdir/.bash_history"\n\
    fi\n\
    export HISTFILE\n\
    unset _histdir\n' > /root/.profile

RUN printf '[ -f ~/.profile ] && . ~/.profile\n' > /root/.zshrc \
    && printf '[ -f ~/.profile ] && . ~/.profile\n' >> /root/.bashrc

USER ${USER_ID}:${GROUP_ID}
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN sed -i 's/^ZSH_THEME=.*/ZSH_THEME="josh"/' ~/.zshrc

USER root
RUN cp /root/.profile ${HOME}/.profile \
    && chown ${USER_ID}:${GROUP_ID} ${HOME}/.profile

USER ${USER_ID}:${GROUP_ID}

RUN sed -i '1i\[ -f ~/.profile ] && . ~/.profile' ~/.zshrc
RUN printf '[ -f ~/.profile ] && . ~/.profile\n' >> ${HOME}/.bashrc

RUN mkdir -p ${HOME}/.vscode-server/

USER ${USERNAME}
########
